using UnityEngine;

public class Enemy : MonoBehaviour
{
    public float moveSpeed = 3f;
    public float fireRate = 2f;
    private float fireCountdown = 0f;
    private Vector3 lastDirection = Vector3.up;
    private int facing = 1;
    Rigidbody2D rb;
    public GameObject enemyBulletPrefab;
    
    void Update()
    {
        transform.Translate(Vector2.left * moveSpeed * Time.deltaTime);
        fireCountdown += Time.deltaTime;
        if(fireCountdown >= fireRate)
        {
            Shoot();
            fireCountdown = 0;
        }
    }

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        float yRot = transform.eulerAngles.y;
        if (Mathf.Approximately(Mathf.DeltaAngle(yRot, 180f), 0f) || transform.localScale.x < 0f)
        {
            facing = -1;
        }
        else
        {
            facing = 1;
        }

        var sr = GetComponentInChildren<SpriteRenderer>();
        if (sr != null)
        {
            sr.flipX = (facing == 1);
        }
    }

    void Shoot()
    {
        if (enemyBulletPrefab != null)
        {
            Vector3 spawnPosition = transform.position;
            spawnPosition.y -= 0.3f;

            GameObject bullet = Instantiate(enemyBulletPrefab, spawnPosition, Quaternion.identity);

            Rigidbody2D rb = bullet.GetComponent<Rigidbody2D>();

            if (rb != null)
            {
                // perpindahan nya memiliki percepatan
                rb.linearVelocity = Vector3.left * 10f;
            }

            bullet.transform.rotation = Quaternion.Euler(0, 0, -90);
        }
    }

    void OnBecameInvisible()
    {
        Destroy(gameObject);
    }

}